"""added public_id columns

Revision ID: 0db3c02391b4
Revises: f0cbccb3ddac
Create Date: 2026-04-13 09:53:15.557034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db3c02391b4'
down_revision: Union[str, None] = 'f0cbccb3ddac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_public_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_public_id')
    op.drop_column('posts', 'thumbnail_public_id')
    # ### end Alembic commands ###
