"""added_new_columns_to_post

Revision ID: 851d60f16aa6
Revises: 
Create Date: 2026-04-04 11:06:00.774604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851d60f16aa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
