"""add thumbnail to posts

Revision ID: f0cbccb3ddac
Revises: f48e462a7bd8
Create Date: 2026-04-06 19:20:08.104241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cbccb3ddac'
down_revision: Union[str, None] = 'f48e462a7bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumbnail')
    # ### end Alembic commands ###
